apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-organizer-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-organizer-app
  template:
    metadata:
      labels:
        app: workshop-organizer-app
    spec:
      containers:
      - name: workshop-organizer-app
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://workshop-organizer-db-service:5432/{{ .Values.db.database }}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
      imagePullSecrets:
      - name: {{ .Values.app.imagePullSecret }}
