apiVersion: v1
kind: Service
metadata:
  name: workshop-organizer-app-service
spec:
  selector:
    app: workshop-organizer-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: LoadBalancer
