apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-organizer-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-organizer-app
  template:
    metadata:
      labels:
        app: workshop-organizer-app
    spec:
      containers:
      - name: workshop-organizer-app
        image: registry.gitlab.com/oc-expert-devops-training/workshop-organizer/snapshot:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://workshop-organizer-db-service:5432/workshop-organizer-database
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: workshop-organizer-db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workshop-organizer-db-secret
              key: password
      imagePullSecrets:
      - name: myregistrykey
